import { execFile, ChildProcess } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import * as Sentry from '@sentry/node';
import { IConverterService } from '../../../domain/interfaces/IConverterService';
import { ConversionError } from '../../../domain/errors/ConversionError';
import { LibreOfficeAdapterConfig, ConversionEngineOptions } from '../../../shared/types';
import { Logger } from '../../logging/Logger';

export class LibreOfficeConverterAdapter implements IConverterService {
  constructor(private readonly config: LibreOfficeAdapterConfig) {}

  public async convert(
    docxBuffer: Buffer,
    options?: ConversionEngineOptions
  ): Promise<Buffer> {
    const uuid = crypto.randomUUID();

    // Ensure temporary directory exists
    if (!fs.existsSync(this.config.temporaryDir)) {
      await fs.promises.mkdir(this.config.temporaryDir, { recursive: true });
    }

    const inputFilePath = path.join(this.config.temporaryDir, `${uuid}.docx`);
    const outputFilePath = path.join(this.config.temporaryDir, `${uuid}.pdf`);

    Logger.info(
      `Starting LibreOffice conversion. Input: ${inputFilePath}, preserveMetadata: ${options?.preserveMetadata}`
    );

    let childProcess: ChildProcess | null = null;
    let timeoutTimer: NodeJS.Timeout | null = null;

    try {
      // 1. Write the input buffer to a temporary file
      await fs.promises.writeFile(inputFilePath, docxBuffer);

      // 2. Setup the conversion promise wrapping the child process execution
      const conversionPromise = new Promise<Buffer>((resolve, reject) => {
        const args = [
          '--headless',
          '--convert-to',
          'pdf',
          '--outdir',
          this.config.temporaryDir,
          inputFilePath
        ];

        childProcess = execFile(this.config.binaryPath, args, async (error, stdout, stderr) => {
          // Clear timeout timer if execution completes before limit
          if (timeoutTimer) {
            clearTimeout(timeoutTimer);
          }

          if (error) {
            Logger.error('LibreOffice execution failed', error, { stdout, stderr });
            const message = stderr ? stderr.trim() : error.message;
            return reject(
              new ConversionError(`LibreOffice failed: ${message}`, 'CLI_EXECUTION_ERROR', 500)
            );
          }

          try {
            // Read output file content
            await fs.promises.access(outputFilePath);
            const pdfBuffer = await fs.promises.readFile(outputFilePath);
            resolve(pdfBuffer);
          } catch (fileErr: any) {
            reject(
              new ConversionError(
                'Converted PDF file was not generated by LibreOffice',
                'CLI_EXECUTION_ERROR',
                500
              )
            );
          }
        });
      });

      // 3. Setup the timeout promise
      const timeoutPromise = new Promise<Buffer>((_, reject) => {
        timeoutTimer = setTimeout(() => {
          if (childProcess) {
            Logger.error(
              `LibreOffice conversion timed out after ${this.config.timeoutMs}ms. Killing process...`
            );
            childProcess.kill('SIGKILL');

            if (process.env.SENTRY_DSN) {
              Sentry.captureException(new Error('LibreOffice conversion timeout exceeded'));
            }
          }
          reject(new ConversionError('LibreOffice conversion timed out', 'ENGINE_TIMEOUT', 504));
        }, this.config.timeoutMs);
      });

      // 4. Race execution against timeout limit
      return await Promise.race([conversionPromise, timeoutPromise]);

    } finally {
      // 5. Cleanup Layer - Ensure temporary files are deleted
      Logger.debug(`Cleaning up temporary files for conversion job: ${uuid}`);

      try {
        if (fs.existsSync(inputFilePath)) {
          await fs.promises.unlink(inputFilePath);
        }
      } catch (err) {
        Logger.warn(`Failed to clean up temporary input file: ${inputFilePath}`, err);
      }

      try {
        if (fs.existsSync(outputFilePath)) {
          await fs.promises.unlink(outputFilePath);
        }
      } catch (err) {
        Logger.warn(`Failed to clean up temporary output file: ${outputFilePath}`, err);
      }
    }
  }
}
