// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertFile(arg1, arg2) {
  return window['go']['main']['App']['ConvertFile'](arg1, arg2);
}

export function GetModelDefinitions() {
  return window['go']['main']['App']['GetModelDefinitions']();
}

export function OpenFileLocation(arg1) {
  return window['go']['main']['App']['OpenFileLocation'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
