// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertFile(arg1:string,arg2:main.AppConfigMetadata):Promise<void>;

export function OpenFileLocation(arg1:string):Promise<void>;

export function SelectFile():Promise<string>;
